apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardgame
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cardgame
      version: "1.0"
  template:
    metadata:
      labels:
        app: cardgame
        version: "1.0"
    spec:
      imagePullSecrets:
      - name: aliyregistrykey
      containers:
      - name: cardgame-app
        image: registry.cn-shenzhen.aliyuncs.com/timedifier/cardgame:19
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
        - name: JHIPSTER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: registry-admin-password
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
        - name: SPRING_SLEUTH_PROPAGATION_KEYS
          value: "x-request-id,x-ot-span-context"
        - name: SERVER_PORT
          value: "8080"
        - name: JAVA_OPTS
          value: " -Xmx1024m -Xms1024m"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://172.22.14.51:8097/card_game?useUnicode=true&characterEncoding=utf8&useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: system
        - name: SPRING_REDIS_HOST
          value: "172.22.14.51"
        - name: SPRING_REDIS_DATABASE
          value: "5"
        - name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
          value: "true"
        - name: JHIPSTER_LOGGING_LOGSTASH_HOST
          value: "172.22.14.95"
        - name: JHIPSTER_LOGGING_LOGSTASH_PORT
          value: "8098"
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1280Mi"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 120
