apiVersion: v1
kind: Service
metadata:
  name: jgw
  namespace: default
  labels:
    app: jgw
spec:
  selector:
    app: jgw
  type: NodePort
  ports:
  - name: http
    nodePort: 30255
    port: 8082
    targetPort: 8082
