apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wechatexperience-php-www-pvc
  namespace: bbs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs